## Overview
This Python application is meant to analyze the CSV files generated by the profiler in its `JUST_PROFILE` mode. These files, in total, can have a big size, so a Big Data based tool was created to load, process and extract useful information from these files in a scalable and friendly way. It uses PySpark to achieve this, and its notebook format eases the debugging and the visualization of the data. `Spark.ipynb` is the main app, though a simpler sequential version called `Pandas.ipynb` was made as well, though it won't work for really large data.

## Requirements and execution steps

It obviously requires Python, Anaconda (for Notebook stuff) and Spark. You can do the following for intergrating PySpark with Jupyter Notebook:
```bash
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook"
```

To execute the notebook, you just have to initialize PySpark and the notebook window will be loaded:
```bash
pyspark
```
Then, choose Spark.ipynb.

### Execution as Python script in cluster
You could just execute the app as a notebook in the cluster, but maybe in that way you won't be able to change the value of `executor-memory` (this happened to me). Also, these steps assume that the cluster uses Spark 1.6. If not, additional changes should be made:

* Load the notebook in local
* Assign True to `USING_CLUSTER` and `AS_A_SERVER_SCRIPT` constants
  - You can also edit other constants and regular expressions if needed
* File -> Download As -> Python (.py)
* Transfer script and CSV files to cluster (`scp` for example)
* Login to cluster (`ssh`) and transfer CSV files to HDFS (`hdfs dfs -put *.csv` or something like that)
* To execute the script:
  - `nohup spark-submit --master yarn --executor-memory 10gb --name my_app Spark.py &> output &`
  - `nohup` allows to maintain the execution even after logging out
  - `executor-memory` must be higher than the total size of the CSV files to be processed
  - After the execution is over, some PNG images will be generated in the execution directory, and `output` file will have some interesting prints about the results
