# Reads CSV generated by RAPL profiler. Nothing special
read_data <- function(filename){
	df <- read.csv(filename, header = TRUE)
	return (df)
}

# Different lines per node
plot_cons_per_node <- function(df){
	nodes <- unique(df$node) # Gets nodes involved in data
	cl <- rainbow(length(nodes))
	legend_labels <- sapply(nodes, function(n) paste("Node ", n))

	plot(0, 0, xlim=c(-0.1, max(df$it)+0.1), ylim=c(-0.1, max(df$val)+0.1), type="n", main="Energy consumption per node", xlab="Iteration", ylab="Joules")
	for(i in 1:length(nodes)){ # One line per node
		df_node <- df[df$node == nodes[i], ] # Gets data for node i
		lines(df_node$it, df_node$val, col = cl[i])
	}
	legend("topleft", legend = legend_labels, col=cl, pch=1) # Adds legend
}

# TODO: different lines per domain. Only one node can be used, or maybe we can aggregate all nodes with a sum or a mean

#setwd("")
df <- read_data("data.csv")
plot_cons_per_node(df)

